#!/bin/sh
# cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
# . $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make 3D mesh in slab of cells.
cd wingMotion_snappyHexMesh
blockMesh
#runApplication snappyHexMesh -overwrite

# Make a 2D mesh by extruding a patch and solve to steady state.
cd ../wingMotion2D_simpleFoam
extrudeMesh
createPatch -overwrite
cp -r 0.orig 0
foamToVTK
#decomposePar
simpleFoam
#reconstructPar
foamToVTK

# Copy the mesh from the steady state case and map the results to a
# mesh motion case, then solve transient.
cd ../wingMotion2D_pimpleDyMFoam
cp -r ../wingMotion2D_simpleFoam/constant/polyMesh constant
cp -r 0.orig 0
mapFields ../wingMotion2D_simpleFoam -sourceTime latestTime -consistent
mv 0/pointDisplacement.unmapped 0/pointDisplacement
cp -r ../wingMotion2D_simpleFoam/0/pointDisplacement 0/pointDisplacement
#decomposePar
#mpirun -np 8 pimpleDyMFoam -parallel >log
pimpleDyMFoam >log
#reconstructPar
foamToVTK


#------------------------------------------------------------------------------
